"""initial business schema

Revision ID: 5271bbb18a1e
Revises:
Create Date: 2026-03-10 16:30:43.055313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5271bbb18a1e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("market", sa.String(length=64), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("ticker", "market", name="uq_companies_ticker_market"),
    )
    op.create_index("ix_companies_name", "companies", ["name"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "report",
                "article",
                "filing",
                "transcript",
                "dataset",
                "other",
                name="source_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_uri", sa.String(length=1024), nullable=True),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("raw_storage_path", sa.String(length=1024), nullable=True),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "parsed",
                "indexed",
                "archived",
                "failed",
                name="document_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_documents_content_hash")),
    )
    op.create_index("ix_documents_published_at", "documents", ["published_at"], unique=False)
    op.create_index(op.f("ix_documents_source_type"), "documents", ["source_type"], unique=False)
    op.create_index(
        "ix_documents_source_type_published_at",
        "documents",
        ["source_type", "published_at"],
        unique=False,
    )
    op.create_table(
        "memory_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "memory_type",
            sa.Enum(
                "theme",
                "content_strategy",
                "user_preference",
                "run_trace",
                name="memory_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("scope_key", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_records")),
    )
    op.create_index(
        "ix_memory_records_memory_type_scope_key",
        "memory_records",
        ["memory_type", "scope_key"],
        unique=False,
    )
    op.create_table(
        "themes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "monitoring", "archived", name="theme_status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_themes")),
        sa.UniqueConstraint("slug", name=op.f("uq_themes_slug")),
    )
    op.create_index("ix_themes_name", "themes", ["name"], unique=False)
    op.create_index("ix_themes_slug", "themes", ["slug"], unique=False)
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section_name", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding_json", sa.JSON(), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_dimension", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_document_chunks_document_id_chunk_index"
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("importance_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"], ["themes.id"], name=op.f("fk_events_theme_id_themes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_theme_id"), "events", ["theme_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "run_type",
            sa.Enum(
                "research",
                "thesis_build",
                "content_generate",
                "memory_refresh",
                name="run_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("theme_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="run_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("input_json", sa.JSON(), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"], ["themes.id"], name=op.f("fk_runs_theme_id_themes"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index("ix_runs_status_started_at", "runs", ["status", "started_at"], unique=False)
    op.create_index(op.f("ix_runs_theme_id"), "runs", ["theme_id"], unique=False)
    op.create_table(
        "theses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "stance",
            sa.Enum("bullish", "bearish", "neutral", name="thesis_stance", native_enum=False),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "invalidated",
                "archived",
                name="thesis_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score IS NULL OR (confidence_score >= 0.0 AND confidence_score <= 1.0)",
            name=op.f("ck_theses_theses_confidence_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"], ["themes.id"], name=op.f("fk_theses_theme_id_themes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theses")),
    )
    op.create_index(op.f("ix_theses_theme_id"), "theses", ["theme_id"], unique=False)
    op.create_index("ix_theses_theme_id_stance", "theses", ["theme_id", "stance"], unique=False)
    op.create_table(
        "citations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=True),
        sa.Column("locator", sa.String(length=255), nullable=True),
        sa.Column("quote_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_citations_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_citations_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citations")),
    )
    op.create_index(op.f("ix_citations_chunk_id"), "citations", ["chunk_id"], unique=False)
    op.create_index(op.f("ix_citations_document_id"), "citations", ["document_id"], unique=False)
    op.create_table(
        "content_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=True),
        sa.Column("thesis_id", sa.Integer(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum(
                "article",
                "report",
                "video_script",
                "thread",
                name="content_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "published",
                "archived",
                "failed",
                name="content_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("body_markdown", sa.Text(), nullable=True),
        sa.Column("meta_json", sa.JSON(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["themes.id"],
            name=op.f("fk_content_assets_theme_id_themes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
            name=op.f("fk_content_assets_thesis_id_theses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_assets")),
    )
    op.create_index(
        "ix_content_assets_content_type_status",
        "content_assets",
        ["content_type", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_assets_theme_id"), "content_assets", ["theme_id"], unique=False
    )
    op.create_index(
        op.f("ix_content_assets_thesis_id"), "content_assets", ["thesis_id"], unique=False
    )
    op.create_table(
        "run_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("step_name", sa.String(length=128), nullable=False),
        sa.Column("agent_name", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="step_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("input_json", sa.JSON(), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_steps_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
    )
    op.create_index(op.f("ix_run_steps_run_id"), "run_steps", ["run_id"], unique=False)
    op.create_table(
        "thesis_evidence_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thesis_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "supporting", "contradicting", "contextual", name="relation_type", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "weight IS NULL OR (weight >= 0.0 AND weight <= 1.0)",
            name=op.f("ck_thesis_evidence_links_thesis_link_weight_range"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_thesis_evidence_links_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
            name=op.f("fk_thesis_evidence_links_thesis_id_theses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thesis_evidence_links")),
        sa.UniqueConstraint(
            "thesis_id",
            "chunk_id",
            "relation_type",
            name="uq_thesis_evidence_links_thesis_chunk_relation",
        ),
    )
    op.create_index(
        op.f("ix_thesis_evidence_links_chunk_id"),
        "thesis_evidence_links",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thesis_evidence_links_thesis_id"),
        "thesis_evidence_links",
        ["thesis_id"],
        unique=False,
    )
    op.create_table(
        "thesis_risks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thesis_id", sa.Integer(), nullable=False),
        sa.Column("risk_title", sa.String(length=255), nullable=False),
        sa.Column("risk_description", sa.Text(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IS NULL OR (severity >= 1 AND severity <= 5)",
            name=op.f("ck_thesis_risks_thesis_risks_severity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
            name=op.f("fk_thesis_risks_thesis_id_theses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thesis_risks")),
    )
    op.create_index(op.f("ix_thesis_risks_thesis_id"), "thesis_risks", ["thesis_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thesis_risks_thesis_id"), table_name="thesis_risks")
    op.drop_table("thesis_risks")
    op.drop_index(op.f("ix_thesis_evidence_links_thesis_id"), table_name="thesis_evidence_links")
    op.drop_index(op.f("ix_thesis_evidence_links_chunk_id"), table_name="thesis_evidence_links")
    op.drop_table("thesis_evidence_links")
    op.drop_index(op.f("ix_run_steps_run_id"), table_name="run_steps")
    op.drop_table("run_steps")
    op.drop_index(op.f("ix_content_assets_thesis_id"), table_name="content_assets")
    op.drop_index(op.f("ix_content_assets_theme_id"), table_name="content_assets")
    op.drop_index("ix_content_assets_content_type_status", table_name="content_assets")
    op.drop_table("content_assets")
    op.drop_index(op.f("ix_citations_document_id"), table_name="citations")
    op.drop_index(op.f("ix_citations_chunk_id"), table_name="citations")
    op.drop_table("citations")
    op.drop_index("ix_theses_theme_id_stance", table_name="theses")
    op.drop_index(op.f("ix_theses_theme_id"), table_name="theses")
    op.drop_table("theses")
    op.drop_index(op.f("ix_runs_theme_id"), table_name="runs")
    op.drop_index("ix_runs_status_started_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_events_theme_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_themes_slug", table_name="themes")
    op.drop_index("ix_themes_name", table_name="themes")
    op.drop_table("themes")
    op.drop_index("ix_memory_records_memory_type_scope_key", table_name="memory_records")
    op.drop_table("memory_records")
    op.drop_index("ix_documents_source_type_published_at", table_name="documents")
    op.drop_index(op.f("ix_documents_source_type"), table_name="documents")
    op.drop_index("ix_documents_published_at", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_companies_name", table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
