from packages.sources.profiles.china_exchange import (
    build_cn_exchange_announcement_generic_profile,
    build_cn_exchange_szse_notice_v1_profile,
)
from packages.sources.profiles.china_industry import (
    build_cn_industry_association_generic_profile,
)
from packages.sources.profiles.china_policy import (
    build_cn_policy_generic_profile,
    build_cn_policy_ndrc_tzgg_v1_profile,
)
from packages.sources.profiles.china_scaleout import (
    build_cn_exchange_cninfo_announcement_v1_profile,
    build_cn_exchange_sse_notice_v1_profile,
    build_cn_industry_caam_news_v1_profile,
    build_cn_industry_ces_report_v1_profile,
    build_cn_park_sh_lingang_tzgg_v1_profile,
    build_cn_policy_anhui_drc_tzgg_v1_profile,
    build_cn_policy_chengdu_jxj_tzgg_v1_profile,
    build_cn_policy_fujian_drc_tzgg_v1_profile,
    build_cn_policy_gd_drc_tzgg_v1_profile,
    build_cn_policy_guangzhou_gxt_tzgg_v1_profile,
    build_cn_policy_hangzhou_fgw_tzgg_v1_profile,
    build_cn_policy_henan_gxt_tzgg_v1_profile,
    build_cn_policy_hubei_gxt_tzgg_v1_profile,
    build_cn_policy_js_gxt_zcwj_v1_profile,
    build_cn_policy_miit_tzgg_v1_profile,
    build_cn_policy_nanjing_gxt_tzgg_v1_profile,
    build_cn_policy_shandong_gxt_tzgg_v1_profile,
    build_cn_policy_shanghai_portal_policy_v1_profile,
    build_cn_policy_shenzhen_gxt_tzgg_v1_profile,
    build_cn_policy_sichuan_drc_tzgg_v1_profile,
    build_cn_policy_state_council_zcwj_v1_profile,
    build_cn_policy_suzhou_drc_tzgg_v1_profile,
    build_cn_policy_wuhan_gxt_tzgg_v1_profile,
    build_cn_policy_zhejiang_drc_tzgg_v1_profile,
    build_cn_project_ccgp_procurement_v1_profile,
    build_cn_project_ggzy_trade_v1_profile,
    build_cn_project_ndrc_approval_v1_profile,
    build_phase1_sample_profiles,
    build_phase2_backbone_profiles,
    build_phase3_provincial_profiles,
    build_phase4_city_park_profiles,
    build_phase4_national_provincial_backbone_profiles,
    build_phase5_industry_profiles,
)


def build_domestic_source_profiles():
    return [
        build_cn_policy_generic_profile(),
        build_cn_policy_ndrc_tzgg_v1_profile(enabled=True),
        build_cn_exchange_announcement_generic_profile(),
        build_cn_exchange_szse_notice_v1_profile(),
        build_cn_industry_association_generic_profile(),
        *build_phase1_sample_profiles(),
        *build_phase2_backbone_profiles(),
        *build_phase3_provincial_profiles(),
        *build_phase4_national_provincial_backbone_profiles(),
        *build_phase4_city_park_profiles(),
        *build_phase5_industry_profiles(),
    ]


__all__ = [
    "build_cn_exchange_announcement_generic_profile",
    "build_cn_exchange_szse_notice_v1_profile",
    "build_cn_industry_association_generic_profile",
    "build_cn_policy_generic_profile",
    "build_cn_policy_ndrc_tzgg_v1_profile",
    "build_cn_policy_state_council_zcwj_v1_profile",
    "build_cn_policy_miit_tzgg_v1_profile",
    "build_cn_policy_anhui_drc_tzgg_v1_profile",
    "build_cn_policy_fujian_drc_tzgg_v1_profile",
    "build_cn_policy_henan_gxt_tzgg_v1_profile",
    "build_cn_exchange_sse_notice_v1_profile",
    "build_cn_exchange_cninfo_announcement_v1_profile",
    "build_cn_policy_gd_drc_tzgg_v1_profile",
    "build_cn_policy_guangzhou_gxt_tzgg_v1_profile",
    "build_cn_policy_js_gxt_zcwj_v1_profile",
    "build_cn_policy_nanjing_gxt_tzgg_v1_profile",
    "build_cn_policy_zhejiang_drc_tzgg_v1_profile",
    "build_cn_policy_hubei_gxt_tzgg_v1_profile",
    "build_cn_policy_sichuan_drc_tzgg_v1_profile",
    "build_cn_policy_shanghai_portal_policy_v1_profile",
    "build_cn_policy_shandong_gxt_tzgg_v1_profile",
    "build_cn_policy_chengdu_jxj_tzgg_v1_profile",
    "build_cn_policy_shenzhen_gxt_tzgg_v1_profile",
    "build_cn_policy_suzhou_drc_tzgg_v1_profile",
    "build_cn_policy_hangzhou_fgw_tzgg_v1_profile",
    "build_cn_policy_wuhan_gxt_tzgg_v1_profile",
    "build_cn_park_sh_lingang_tzgg_v1_profile",
    "build_cn_industry_caam_news_v1_profile",
    "build_cn_industry_ces_report_v1_profile",
    "build_cn_project_ccgp_procurement_v1_profile",
    "build_cn_project_ggzy_trade_v1_profile",
    "build_cn_project_ndrc_approval_v1_profile",
    "build_phase1_sample_profiles",
    "build_phase2_backbone_profiles",
    "build_phase3_provincial_profiles",
    "build_phase4_national_provincial_backbone_profiles",
    "build_phase4_city_park_profiles",
    "build_phase5_industry_profiles",
    "build_domestic_source_profiles",
]
